server:
 port: 8080

spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: true
  application:
    name: login-service

  redis:
    host: 192.168.1.214
    port: 6380
    password: yesXAu3tMrJmRXRfQYim1sm2s7CPqhjM

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30