server:
 port: 8080

spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: true
  application:
    name: login-service
  datasource:
    url: jdbc:h2:C:/data/sampledata
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30