server:
 port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: SYSTEM
    password: password
    driver.class-name: oracle.jdbc.OracleDriver
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: true
  application:
    name: login-service

mybatis:
  mapper-locations: classpath*:com/example/Login/mapper/**.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30