CREATE TABLE IF NOT EXISTS `Users`;

CREATE TABLE `Users` (
  `Email` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(256) NOT NULL,
  PRIMARY KEY(`Email`)
)

CREATE TABLE IF NOT EXISTS `Sessions`;

CREATE TABLE `Sessions` (
  `Email` VARCHAR(100) NOT NULL,
  `Sessions` VARCHAR(100) NOT NULL,
  PRIMARY KEY(`Email`)
)